
medical_warehouse:
  target: dev
  outputs:
    dev:
      type: postgres
      threads: 1
      host: "{{ env_var('DB_HOST', 'localhost') }}"
      port: {{ env_var('DB_PORT', 5432) | as_number }}
      user: "{{ env_var('DB_USER', 'postgres') }}"
      pass: "{{ env_var('DB_PASSWORD', 'password') }}"
      dbname: "{{ env_var('DB_NAME', 'medical_warehouse') }}"
      schema: public
